### ISSUE TITLE
Create working directory for user during configuration proces

### ISSUE THREAD

**Issue by k0gen** [yzernik/agora-wrapper#6]
I have just installed Agora and configured it to poin to `satoshi` directory in filebrowser and here is the result:

```
The service agora has crashed with the following exit code: 1 Details: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ error: IO error accessing filesystem at `/mnt/filebrowser/satoshi`: No such file or directory (os error 2) 
```
For now the instructions should include information about creating directory before running the service.
In future simple `mkdir  /mnt/filebrowser/<directoryname-from-configuration>` would be great.

**Comment by yzernik** [comment]
@k0gen I just tried opening a PR to create the missing directory: https://github.com/yzernik/agora-wrapper/pull/7

```
mkdir -p /mnt/filebrowser/${FILES_DIR}
```

Then I get this error:
```
2022-06-04T04:52:21.842026Z mkdir: cannot create directory '/mnt/filebrowser/satoshi': Read-only file system
```

Do you know if there is any way to get permission to create this directory?

**Comment by k0gen** [comment]
Try now #8

**Comment by yzernik** [comment]
Thanks @k0gen 

The directory is auto-created now: https://github.com/yzernik/agora-wrapper/pull/7
